### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by KevinP-T** [AlvaroR15/MercadoLiebre#1]
### Header
* La primera sección del header esta perfecta estructuralmente
* Se utiliza correctamente un `nav` para la barra de navegación
* El logo me redirige al home por medio de una etiqueta `a`
### Main
* Los artículos están en su correspondiente etiqueta `article`
* Están dentro de su `section`
### Footer
* Me parece bien elegidas las etiquetas en el Footer

## 2.
* Los iconos dentro del footer se desalinean en modo tablet `1018x760`
* Me parece que quedan bien con el padding y tamaños dados
## 3.
* Se adapta bien visualmente
* En celular no se adapto los hovers 
* Los iconos en modo tablet que resalte arriba 
* En pantallas Extra grandes la fuente queda un poco chica
## 4.
* Su cuenta con formulario de registro
## 5.
* Su cuenta con formulario de Login
## 6.
* Si se muestran mensajes de error en los inputs
## 7.
* El search bar si es un formulario
## 8.
* Si se utilizan animaciones y propiedades de css
## 9.
* Me parece que el uso del color en los iconos y paginas se adaptan muy bien, su código refleja una pagina muy limpia y bien programada.
## 10.
* Mejorar un poco, por mencionar algo, en la responsividad de la pagina

**Comment by AlvaroR15** [comment]
Gracias crack, saludos!
